---
eck-elasticsearch:
  enabled: true
  version: 7.17.9
  fullnameOverride: dht-elastic
  annotations:
    eck.k8s.elastic.co/license: basic
  nodeSets:
  - name: masters
    count: 3
    config:
      node.roles: ["master"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            # storage: 1Ti
            storage: 5Gi
        # storageClassName: local-storage
  - name: hot
    count: 2
    config:
      node.roles: ["data_hot", "data_content", "ingest"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 100m
            limits:
              memory: 3Gi
              cpu: 2
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            # storage: 1Ti
            storage: 8Gi
        # storageClassName: local-storage
  - name: cold
    count: 1
    config:
      node.roles: ["data_cold"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        # storageClassName: local-storage

eck-kibana:
  enabled: true
  version: 7.17.9
  fullnameOverride: dht-kibana
  annotations:
    eck.k8s.elastic.co/license: basic
  spec:
    elasticsearchRef:
      name: dht-elastic
    count: 1
    podTemplate:
      spec:
        containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 2
    http:
      service:
        spec:
          port: 5601
          targetPort: http
          type: LoadBalancer

